<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="82904" started-at="2018-10-09T14:27:01Z" finished-at="2018-10-09T14:28:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82904" started-at="2018-10-09T14:27:01Z" finished-at="2018-10-09T14:28:24Z">
      <class name="hybrid.DDTExcel">
        <test-method status="FAIL" signature="DemoProject(java.lang.String, java.lang.String)[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="DemoProject" duration-ms="13209" started-at="2018-10-09T19:57:01Z" data-provider="testdata" finished-at="2018-10-09T19:57:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[usernamepassword]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ password]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at hybrid.DDTExcel.DemoProject(DDTExcel.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method status="PASS" signature="ProgramTermination()[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="ProgramTermination" is-config="true" duration-ms="1084" started-at="2018-10-09T19:57:14Z" finished-at="2018-10-09T19:57:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
        <test-method status="PASS" signature="DemoProject(java.lang.String, java.lang.String)[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="DemoProject" duration-ms="14012" started-at="2018-10-09T19:57:15Z" data-provider="testdata" finished-at="2018-10-09T19:57:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edureka]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edureka123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method status="PASS" signature="ProgramTermination()[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="ProgramTermination" is-config="true" duration-ms="1068" started-at="2018-10-09T19:57:29Z" finished-at="2018-10-09T19:57:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
        <test-method status="PASS" signature="DemoProject(java.lang.String, java.lang.String)[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="DemoProject" duration-ms="14206" started-at="2018-10-09T19:57:31Z" data-provider="testdata" finished-at="2018-10-09T19:57:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method status="PASS" signature="ProgramTermination()[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="ProgramTermination" is-config="true" duration-ms="1094" started-at="2018-10-09T19:57:45Z" finished-at="2018-10-09T19:57:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
        <test-method status="FAIL" signature="DemoProject(java.lang.String, java.lang.String)[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="DemoProject" duration-ms="11624" started-at="2018-10-09T19:57:46Z" data-provider="testdata" finished-at="2018-10-09T19:57:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Admin123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at hybrid.DDTExcel.DemoProject(DDTExcel.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method status="PASS" signature="ProgramTermination()[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="ProgramTermination" is-config="true" duration-ms="1108" started-at="2018-10-09T19:57:57Z" finished-at="2018-10-09T19:57:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
        <test-method status="FAIL" signature="DemoProject(java.lang.String, java.lang.String)[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="DemoProject" duration-ms="11415" started-at="2018-10-09T19:57:59Z" data-provider="testdata" finished-at="2018-10-09T19:58:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Admin124]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at hybrid.DDTExcel.DemoProject(DDTExcel.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method status="PASS" signature="ProgramTermination()[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="ProgramTermination" is-config="true" duration-ms="1106" started-at="2018-10-09T19:58:10Z" finished-at="2018-10-09T19:58:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
        <test-method status="FAIL" signature="DemoProject(java.lang.String, java.lang.String)[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="DemoProject" duration-ms="11348" started-at="2018-10-09T19:58:11Z" data-provider="testdata" finished-at="2018-10-09T19:58:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Admin125]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at hybrid.DDTExcel.DemoProject(DDTExcel.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method status="PASS" signature="ProgramTermination()[pri:0, instance:hybrid.DDTExcel@7cd62f43]" name="ProgramTermination" is-config="true" duration-ms="1100" started-at="2018-10-09T19:58:22Z" finished-at="2018-10-09T19:58:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
      </class> <!-- hybrid.DDTExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
